// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAywLgCKXSDurCG6y5fWoz6b28ppP9VjNY',
    appId: '1:463443440:web:0d5ba0b3119c683e07b935',
    messagingSenderId: '463443440',
    projectId: 'learning-app-acb89',
    authDomain: 'learning-app-acb89.firebaseapp.com',
    storageBucket: 'learning-app-acb89.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAJNwIdZBebehDW70xagpnnaPGaN1mzXRQ',
    appId: '1:463443440:android:1e671948771a28ac07b935',
    messagingSenderId: '463443440',
    projectId: 'learning-app-acb89',
    storageBucket: 'learning-app-acb89.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBW_n6GDz9aFcQSjm1CeUOjvgTvWGzordk',
    appId: '1:463443440:ios:d8b843e8d80890c907b935',
    messagingSenderId: '463443440',
    projectId: 'learning-app-acb89',
    storageBucket: 'learning-app-acb89.appspot.com',
    iosBundleId: 'com.example.blocCounter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBW_n6GDz9aFcQSjm1CeUOjvgTvWGzordk',
    appId: '1:463443440:ios:32d90099ca3b42d407b935',
    messagingSenderId: '463443440',
    projectId: 'learning-app-acb89',
    storageBucket: 'learning-app-acb89.appspot.com',
    iosBundleId: 'com.example.blocCounter.RunnerTests',
  );
}
